/**
 * ============================================================
 *  HOSSAM ABDEL-GAWAD — PORTFOLIO CONFIG
 *  Generated by Admin Dashboard · ٢٣‏/٤‏/٢٠٢٦
 * ============================================================
 */

const CONFIG = {

  identity: {
    name: "Hossam Abdel-Gawad",
    nameAr: "حسام عبد الجواد",
    title: "Multi-disciplinary Creative",
    tagline: "Graphic Design · Cinematic Editing · Marketing",
    subtag: "Luxury Content Powered by AI",
    bio: "I craft high-end visual experiences that blur the line between art and strategy — blending cinematic storytelling, bold graphic design, and AI-driven creativity to build brands that command attention.",
    email: "hossam@example.com",
    location: "Egypt",
  },

  theme: {
    accent:        "#C9A96E",
    accentLight:   "#E8CFA0",
    accentGlow:    "#C9A96E40",
    bg:            "#080808",
    bgCard:        "#111111",
    bgCardHover:   "#181818",
    surface:       "#1A1A1A",
    border:        "#222222",
    textPrimary:   "#F5F0E8",
    textSecondary: "#888880",
    textMuted:     "#444440",
  },

  social: {
    behance:   "https://www.behance.net/ef55c0e3",
    linkedin:  "",
    instagram: "https://www.instagram.com/3bgwed/?hl=ar",
    youtube:   "",
    vimeo:     "",
    email:     "hossam@example.com",
  },

  videos: [
    {
        "id": "dQw4w9WgXcQ",
        "platform": "youtube",
        "title": "Brand Film — Luxury Fashion",
        "category": "Cinematic Editing",
        "tags": [
            "Luxury",
            "Fashion",
            "AI"
        ],
        "featured": true
    },
    {
        "id": "dQw4w9WgXcQ",
        "platform": "youtube",
        "title": "Product Launch — High-End Watch",
        "category": "Cinematic Editing",
        "tags": [
            "Product",
            "Luxury"
        ],
        "featured": false
    },
    {
        "id": "dQw4w9WgXcQ",
        "platform": "youtube",
        "title": "Social Media Reel — Beauty Brand",
        "category": "Marketing",
        "tags": [
            "Social",
            "Beauty"
        ],
        "featured": false
    }
],

  designs: [
    {
        "src": "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=400",
        "title": "Brand Identity — Noir Parfum",
        "category": "Graphic Design",
        "tags": [
            "Branding",
            "Luxury",
            "AI"
        ],
        "featured": true
    },
    {
        "src": "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400",
        "title": "Editorial Layout — Fashion Magazine",
        "category": "Graphic Design",
        "tags": [
            "Editorial",
            "Print"
        ],
        "featured": false
    },
    {
        "src": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
        "title": "Campaign — AI Generated Visuals",
        "category": "AI + Design",
        "tags": [
            "AI",
            "Campaign"
        ],
        "featured": true
    },
    {
        "src": "https://www.behance.net/gallery/236920717/Social-Media-Design-Al-Rayyan-Perfume",
        "title": "Social Media Design | Al Rayyan Perfume",
        "category": "Graphic Design",
        "tags": [],
        "featured": false
    }
],

  certificates: [
    {
        "title": "Strategy Consulting Essentials",
        "issuer": "McKinsey & Company",
        "logo": "M",
        "date": "2024",
        "credential": "#",
        "color": "#1a73e8",
        "featured": true
    },
    {
        "title": "Google Digital Marketing",
        "issuer": "Google",
        "logo": "G",
        "date": "2024",
        "credential": "#",
        "color": "#EA4335",
        "featured": false
    }
],

  services: [
    {
        "icon": "◈",
        "title": "Graphic Design",
        "desc": "Brand identities, editorial layouts, and visual systems built for luxury markets."
    },
    {
        "icon": "◉",
        "title": "Cinematic Editing",
        "desc": "Film-quality video production and post-processing for brands that demand excellence."
    },
    {
        "icon": "◇",
        "title": "AI-Powered Content",
        "desc": "Cutting-edge visuals and campaigns leveraging the latest AI tools."
    },
    {
        "icon": "◈",
        "title": "Marketing Strategy",
        "desc": "High-impact campaigns crafted with data-driven insight and creative boldness."
    }
],

  display: {
    gridColumns: 3,
    showVideoSection: true,
    showDesignSection: true,
    showCertificates: true,
    showServices: true,
    enableCursor: true,
    enableParticles: true,
    enableScrollAnimations: true,
  },

  stats: {
    projects: "50+",
    experience: "5+",
    clients: "30+",
  },

};

(function applyTheme() {
  const root = document.documentElement;
  const t = CONFIG.theme;
  root.style.setProperty("--accent",        t.accent);
  root.style.setProperty("--accent-light",  t.accentLight);
  root.style.setProperty("--accent-glow",   t.accentGlow);
  root.style.setProperty("--bg",            t.bg);
  root.style.setProperty("--bg-card",       t.bgCard);
  root.style.setProperty("--bg-card-hover", t.bgCardHover);
  root.style.setProperty("--surface",       t.surface);
  root.style.setProperty("--border",        t.border);
  root.style.setProperty("--text-primary",  t.textPrimary);
  root.style.setProperty("--text-secondary",t.textSecondary);
  root.style.setProperty("--text-muted",    t.textMuted);
})();