/**
 * ============================================================
 *  HOSSAM ABDEL-GAWAD — PORTFOLIO CONFIG
 *  Generated by Admin Dashboard · ٢٤‏/٤‏/٢٠٢٦
 * ============================================================
 */

const CONFIG = {

  identity: {
    name: "Hossam Abdel-Gawad",
    nameAr: "حسام عبد الجواد",
    title: "Multi-disciplinary Creative",
    tagline: "Graphic Design · Cinematic Editing · Marketing",
    subtag: "Luxury Content Powered by AI",
    bio: "I craft high-end visual experiences that blur the line between art and strategy — blending cinematic storytelling, bold graphic design, and AI-driven creativity to build brands that command attention.",
    email: "hossam.creative1@gmail.com",
    location: "Egypt",
  },

  theme: {
    accent:        "#C9A96E",
    accentLight:   "#E8CFA0",
    accentGlow:    "#C9A96E40",
    bg:            "#080808",
    bgCard:        "#111111",
    bgCardHover:   "#181818",
    surface:       "#1A1A1A",
    border:        "#222222",
    textPrimary:   "#F5F0E8",
    textSecondary: "#888880",
    textMuted:     "#444440",
  },

  social: {
    behance:   "https://www.behance.net/ef55c0e3",
    linkedin:  "",
    instagram: "https://www.instagram.com/3bgwed/?hl=ar",
    youtube:   "https://www.youtube.com/@3bgwed2003",
    vimeo:     "",
    email:     "hossam.creative1@gmail.com",
  },

  videos: [
    {
        "id": "Ye7b_9H83wA",
        "platform": "youtube",
        "title": "\"أول فيديو لي على البرمير - هل يستحق المشاهدة؟ 🎬🔥\"",
        "category": "Video",
        "tags": [],
        "featured": true
    }
],

  designs: [
    {
        "src": "https://res.cloudinary.com/dlv72mxl5/image/upload/v1776959339/474092009_122208513122210045_7246867498698929885_n_hs5fnl.jpg",
        "title": "تصميم عيادة اسنان|Dental clinic design",
        "category": "Graphic Design",
        "tags": [],
        "featured": false
    },
    {
        "src": "https://res.cloudinary.com/dlv72mxl5/image/upload/v1776959340/hossam-abdel_gawx-_lzgabt.jpg",
        "title": "بوستر",
        "category": "Graphic Design",
        "tags": [],
        "featured": false
    },
    {
        "src": "https://res.cloudinary.com/dlv72mxl5/image/upload/v1776988044/%D8%A7%D9%84%D9%8A%D9%88%D9%85_%D8%A7%D9%84%D9%88%D8%B7%D9%86%D9%8AArtboard_1_c8tno2.jpg",
        "title": "اليوم الوطني السعودي ال95 |Saudi National Day 95",
        "category": "Graphic Design",
        "tags": [],
        "featured": false
    },
    {
        "src": "https://res.cloudinary.com/dlv72mxl5/image/upload/v1776988039/%D8%A7%D9%84%D9%8A%D9%88%D9%85_%D8%A7%D9%84%D9%88%D8%B7%D9%86%D9%8AArtboard_2_uolmxt.jpg",
        "title": "اليوم الوطني السعودي ال95 |Saudi National Day 95",
        "category": "Graphic Design",
        "tags": [],
        "featured": false
    },
    {
        "src": "https://res.cloudinary.com/dlv72mxl5/image/upload/v1776988054/%D8%A7%D9%84%D9%8A%D9%88%D9%85-%D8%A7%D9%84%D9%88%D8%B7%D9%86%D9%8A_tmntxr.gif",
        "title": "اليوم الوطني السعودي ال95 |Saudi National Day 95",
        "category": "Graphic Design",
        "tags": [],
        "featured": false
    }
],

  certificates: [
    {
        "title": "Strategy Consulting Essentials",
        "issuer": "McKinsey & Company",
        "logo": "M",
        "date": "2024",
        "credential": "#",
        "color": "#1a73e8",
        "featured": true
    },
    {
        "title": "Google Digital Marketing",
        "issuer": "Google",
        "logo": "G",
        "date": "2024",
        "credential": "#",
        "color": "#EA4335",
        "featured": false
    },
    {
        "title": "أساسيات الرسم للتحر يك",
        "issuer": "Yanfaa",
        "logo": "Y",
        "date": "2024",
        "credential": "https://drive.google.com/file/d/1hiKbUNzPDkijNq0uGnvULbRdv9Ffzh4o/view?usp=drive_link",
        "color": "#1E2B58",
        "featured": false
    },
    {
        "title": "Reels From Scratch To Screen",
        "issuer": "Yanfaa",
        "logo": "Y",
        "date": "2024",
        "credential": "https://drive.google.com/file/d/1r9Xel3dTGHLS72E30oFYT7w0-_EnIVNY/view?usp=drive_link",
        "color": "#1E2B58",
        "featured": false
    }
],

  services: [
    {
        "icon": "◈",
        "title": "Graphic Design",
        "desc": "Brand identities, editorial layouts, and visual systems built for luxury markets."
    },
    {
        "icon": "◉",
        "title": "Cinematic Editing",
        "desc": "Film-quality video production and post-processing for brands that demand excellence."
    },
    {
        "icon": "◇",
        "title": "AI-Powered Content",
        "desc": "Cutting-edge visuals and campaigns leveraging the latest AI tools."
    },
    {
        "icon": "◈",
        "title": "Marketing Strategy",
        "desc": "High-impact campaigns crafted with data-driven insight and creative boldness."
    }
],

  display: {
    gridColumns: 3,
    showVideoSection: true,
    showDesignSection: true,
    showCertificates: true,
    showServices: true,
    enableCursor: true,
    enableParticles: true,
    enableScrollAnimations: true,
  },

  stats: {
    projects: "50+",
    experience: "3+",
    clients: "30+",
  },

};

(function applyTheme() {
  const root = document.documentElement;
  const t = CONFIG.theme;
  root.style.setProperty("--accent",        t.accent);
  root.style.setProperty("--accent-light",  t.accentLight);
  root.style.setProperty("--accent-glow",   t.accentGlow);
  root.style.setProperty("--bg",            t.bg);
  root.style.setProperty("--bg-card",       t.bgCard);
  root.style.setProperty("--bg-card-hover", t.bgCardHover);
  root.style.setProperty("--surface",       t.surface);
  root.style.setProperty("--border",        t.border);
  root.style.setProperty("--text-primary",  t.textPrimary);
  root.style.setProperty("--text-secondary",t.textSecondary);
  root.style.setProperty("--text-muted",    t.textMuted);
})();
